# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Christopher Milne - Technical Writer
email: miln0068@algonquinlive.com
description: > # this means to ignore newlines until "baseurl:"
  This space is for Christopher Milne's technical writing resume.
baseurl: "https://chris-milne.github.io/Posts" # the subpath of your site, e.g. /blog
url: "https://chris-milne.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

gems:
  - jekyll-paginate
  # other gems
permalink: /Posts/:year/:month/:day/:title
